### ISSUE TITLE
migrate action-go-release into this repo

### ISSUE THREAD

**Issue by greenkiwi** [open-turo/actions-go#2]
Move https://github.com/open-turo/action-go-release into this repository.

We will now have only once core repo for high level golang actions.

**Comment by dgschwindturo** [comment]
Hi @greenkiwi , this should have been addressed when PR 4 against this repo was merged.

**Comment by tagoro9** [comment]
This is now fixed and this repo is using https://github.com/open-turo/actions-release internally
